spring:
  data:
    mongodb:
      database: server-health
      port: 27017
      host: localhost
      
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

server:
  port: 8081