server:
  port: 8080
 
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_character
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    